version: '3.3'
services:
  database:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'dartend'
      MYSQL_USER: 'dartend_user'
      MYSQL_PASSWORD: 'dartend_pass'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './volumes/mysql:/var/lib/mysql'
      - './db.sql:/docker-entrypoint-initdb.d/1.sql'
